/** 菲律宾银行/钱包编码（bankName 与 bankCode 保持一致） */
export const PHILIPPINE_BANK_OPTIONS = [
  'ALLBANK(A Thirft Bank)',
  'Asia United Bank Corporation',
  'BanKo, A Subsidiary of BPI',
  'Bangko Mabuhay',
  'Bank of China',
  'Bank of Commerce',
  'BDO Network Bank',
  'BDO Unibank',
  'Binangonan Rural Bank / BRBDigital',
  'BPI Bank',
  'Camalig Bank',
  'CARD Bank',
  'CARD SME Bank',
  'Cebuana Lhuillier Bank / Cebuana Xpress',
  'China Bank Savings',
  'CIMB Philippines, Inc.',
  'CIS Bayad Center / Bayad',
  'CTBC Bank (Philippines) Corporation',
  'DCPay / COINS.PH',
  'Development Bank of the Philippines',
  'Dumaguete City Development Bank',
  'Dungganon Bank',
  'East West Banking Corporation',
  'East West Rural Bank / Komo',
  'Entrepreneur Rural Bank, Inc./ENTRP',
  'Equicom Savings Bank, Inc.',
  'gcash',
  'GoTyme Bank',
  'GrabPay',
  'Infoserve / Nationlink',
  'I-Remit / iCASH',
  'ISLA Bank',
  'LANDBANK / OFBank',
  'Legazpi Saving Bank',
  'Luzon Development Bank',
  'Malayan Bank Savings and Mortgage Bank, Inc.',
  'Maybank Philippnies',
  'Metropolitan Bank and Trust Co',
  'Mindanao Consolidated CoopBank',
  'Netbank',
  'OmniPay, Inc.',
  'Pacific Ace Savings Bank',
  'PalawanPay',
  'Partner Rural Bank (Cotabato), Inc.',
  'paymaya',
  'Philippine Bank of Communications',
  'Philippine Business Bank',
  'Philippine National Bank',
  'Philippine Savings Bank',
  'Philippine Trust Company',
  'Producers Bank',
  'QUEENBANK',
  'Quezon Capital Rural Bank',
  'RCBC/DiskarTech',
  'Robinsons Bank Corporation',
  'Rural Bank of Guinobatan / Asenso',
  'Seabank',
  'Security Bank Corporation',
  'ShopeePay',
  'STANDARD CHARTERED BANK',
  'Starpay',
  'Sterling Bank of Asia',
  'Sun Savings Bank',
  'TayoCash',
  'Tonik Bank',
  'UCPB Savings Bank',
  'United Coconut Planters Bank (UCPB)',
  'USSC Money Services',
  'Wealth Development Bank',
  'Zybi Tech Inc. / JuanCash'
]
